#!/usr/bin/env python

import sys, os, gtk, indicate, pynotify, rfc822, string, email.header, email.charset

# This utility monitors maildirs and emits a notification when new messages arrive.
# It sits in ubuntu's messaging menu.

# Determine the exec directory. From this we can decide if we are
# system-wide or local
EXEC_DIR    = os.path.abspath(os.path.dirname(sys.argv[0]))

EXEC_NAME   = "maildir-indicator"

DEBUG_ON    = True

def DEBUG(message):
    if DEBUG_ON == True:
        print message

# defaults
MAX_HEADER_LENGTH = 30
MAX_NOTIFY = 10
CHECK_FREQUENCY = 300

# Indicator entry requires a desktop. It uses it for name & icon.
# As this will be passed to an external process, the file must be an absolute path.
# If system-wide, the .desktop file will not be in the same directory
if ( EXEC_DIR == "/usr/bin" ):
    GLOBAL_CONFIG       = "/etc/" + EXEC_NAME + ".conf"
    MUA_DESKTOP_FILE    = "/etc/xdg/autostart/" + EXEC_NAME + ".desktop"
else:
    GLOBAL_CONFIG       = EXEC_DIR + "/" + EXEC_NAME + ".conf"
    MUA_DESKTOP_FILE    = EXEC_DIR + "/" + EXEC_NAME + ".desktop"


if ( os.environ.get('XDG_CONFIG_HOME') != None ):
    USER_CONFIG         = os.environ['XDG_CONFIG_HOME'] + "/" + EXEC_NAME + ".conf"
else:
    USER_CONFIG         = os.environ['HOME'] + "/.config/" + EXEC_NAME + ".conf"

# Exec global config file.
# Position debug statement inside block (twice) so we don't accidentally output a
# message if debugging is off
if ( os.path.isfile( GLOBAL_CONFIG ) ):
    execfile( GLOBAL_CONFIG )
    DEBUG( "Including GLOBAL_CONFIG  : " + GLOBAL_CONFIG )
    DEBUG( " |- OK" )
else:
    DEBUG( "Including GLOBAL_CONFIG  : " + GLOBAL_CONFIG )
    DEBUG( " |- DOES NOT EXIST" )

# Exec user config file.
if ( os.path.isfile( USER_CONFIG ) ):
    execfile( USER_CONFIG )
    DEBUG( "Including USER_CONFIG    : " + USER_CONFIG )
    DEBUG( " |- OK" )
else:
    DEBUG( "Including USER_CONFIG    : " + USER_CONFIG )
    DEBUG( " |- DOES NOT EXIST" )

# Let the user know what values are being used:
DEBUG( "CONFIGURATION" )
DEBUG( " |- CHECK_FREQUENCY      : " + str(CHECK_FREQUENCY) )
DEBUG( " |- MUA_DESKTOP_FILE     : " + MUA_DESKTOP_FILE )
DEBUG( " |- MUA_LAUNCH_COMMAND   : " + MUA_LAUNCH_COMMAND )
DEBUG( " |- MAX_HEADER_LENGTH   : " + str(MAX_HEADER_LENGTH) )
DEBUG( " |- MAX_NOTIFY   : " + str(MAX_NOTIFY) )

class mailIndicator:
    # List of seen files per-directory
    notified_messages={}

    def __init__(self):

        # Register with indicator applet
        DEBUG("Registering with Indicator Applet")
        self.indicator = indicate.indicate_server_ref_default()
        self.indicator.set_type("message.mail")
        self.indicator.set_desktop_file(MUA_DESKTOP_FILE)
        self.indicator.connect("server-display", self.indicator_clicked)
        self.indicators = {}

        # Register with notification system
        if pynotify.init( ("Maildir Indicator") ):
            DEBUG("Registered with Notification system")
            self.notify = True
        else:
            DEBUG("Failed Registration with Notification system. Continuing without notifications")
            self.notify = False

        # Build list of maildir indicators
        self.buildMenus()

    def buildMenus(self):
        DEBUG("BUILDING maildir list")
        # Loop through the maildirs configured above
        for name, path in MAILDIRS.iteritems():
            DEBUG( " |- " + name )
            # Create mailbox indicator
            new_indicator = indicate.Indicator()
            new_indicator.set_property("name", name)
            new_indicator.set_property("count", "0")
            new_indicator.label = name
            new_indicator.connect("user-display", self.maildir_clicked)

            # Always show it
            new_indicator.show()

            # Save it for later
            self.indicators[name] = new_indicator

            # Set a blank notified messages array to avoid key err later
            self.notified_messages[name] = []

    def run(self):
        # This is the main loop
        self.check_mailbox()
        gtk.timeout_add(CHECK_FREQUENCY * 1000, self.check_mailbox)
        gtk.main()

    def maildir_clicked(self, widget, data=None):
        # User clicked on a maildir entry. We don't open anything,
        # just mark remove the attention flag.
        name = widget.get_property("name")
        count = widget.get_property("count")
        DEBUG("Removing attention flag from " + count + " messages in " + name)

        # Mark this mail box as no-longer needing attention.
        widget.set_property("draw-attention", "false")
        return True

    def indicator_clicked(self, widget,data=None):
        # Run MUA_LAUNCH_COMMAND
        os.system(MUA_LAUNCH_COMMAND)

    def check_mailbox(self):
        DEBUG("CHECKING for new mail")

        noticecount = 0
        message_data = {} # { sender: [subject, subject, subject], ...} 

        # Check mailboxes for new mail
        for name, path in MAILDIRS.iteritems():
            try:
                # Get a list of all new mail
                # TODO: Should check for unseen mail in cur?
                messages = os.listdir( os.path.join(path, "new" ) )
                count_new       = len( messages )
                count_brandnew  = 0

                # get sender names and titles for new messages
                for message in messages:
                    if message not in self.notified_messages[name]:
                        # Count brand-new message
                        count_brandnew += 1
                        if (count_brandnew <= MAX_NOTIFY):
                            # build an rfc822 object to access email data
                            fh = open( os.path.join(path, "new", message) )
                            parsed_message = rfc822.Message(fh)
                            fh.close()
                            
                            sender = get_parsed_header(parsed_message, "From").strip('"')
                            subject = get_parsed_header(parsed_message, "Subject")

                            if message_data.has_key(sender):
                                message_data[sender].append(subject)
                            else:
                                message_data[sender] = [subject]


                    
                # Save this maildir's list of notified messages
                self.notified_messages[name] = messages

                # If there are no messages, then remove any attention flag
                if ( count_new == 0 ):
                    self.indicators[name].set_property("draw-attention", "false")
                # If there are brand-new messages, then set attention to true
                # Also add them to the notice
                elif ( count_brandnew > 0 ):
                    self.indicators[name].set_property("draw-attention", "true")
                    noticecount += count_brandnew
                # Implied default case is to leave the attention flag as-is
            except OSError:
                # If there was an error, set error
                count = "error"

            DEBUG( " |- " + name + ": " 
                    + str(count_new)            + " new messages detected, "
                    + str(count_brandnew) + " brand-new messages detected" )


            # Indicate number of new messages
            self.indicators[name].set_property("count", str(count_new))

        if ( noticecount > 0 ):
            notify_title = str(noticecount) + " new email messages\n"
            # format our notification to
            # Sender Name: subject1, subject 2
            # Sender Name2: subject3, subject 4
            message_data = map( 
                lambda x: 
                    "%s:\n\t%s" % (x, string.join(message_data[x], "\n\t") ), 
                    message_data.keys() )
            notify_text = string.join(message_data, "\n")

            self.sendnotify(notify_title, notify_text)

        return True

    def sendnotify(self, title, message):
        if not self.notify:
            DEBUG("NOT Sending notification")
            return True

        DEBUG( "Sending notification" )
        n = pynotify.Notification(title, message, "notification-message-email")
        n.show()

        return n

def get_parsed_header(parsed_message, header_name):
    # I hate charsets!
    # parsed_message should be an rfc822 object. getheader returns a list
    # of (value, encoding) tuples. Should return header as decoded unicode 
    # string.
    header = parsed_message.getheader(header_name)
    header = email.header.decode_header(header)

    if  header[0][1] != None: # charset specified
        header = unicode(header[0][0], header[0][1], "ignore")
    else: # no charset specified
        header = unicode(header[0][0], "utf-8", "ignore")

    if header_name == "From": 
        # Remove email address and just give name
        header = header.split(" <", 1)[0]

    if len(header) > MAX_HEADER_LENGTH: 
        header = header[:MAX_HEADER_LENGTH-3] + "..."

    return header
       

if __name__ == "__main__":
    indicator = mailIndicator()
    indicator.run()
