#!/usr/bin/env python

import sys, os, gtk, indicate, pynotify

# This utility monitors maildirs and emits a notification when new messages arrive.
# It sits in ubuntu's messaging menu.

# Determine the exec directory. From this we can decide if we are
# system-wide or local
EXEC_DIR    = os.path.abspath(os.path.dirname(sys.argv[0]))

EXEC_NAME   = "maildir-indicator"

DEBUG_ON    = True;

def DEBUG(message):
    if DEBUG_ON == True:
        print message

# Indicator entry requires a desktop. It uses it for name & icon.
# As this will be passed to an external process, the file must be an absolute path.
# If system-wide, the .desktop file will not be in the same directory
if ( EXEC_DIR == "/usr/bin" ):
    GLOBAL_CONFIG       = "/etc/" + EXEC_NAME + ".conf"
    MUA_DESKTOP_FILE    = "/etc/xdg/autostart/" + EXEC_NAME + ".desktop"
else:
    GLOBAL_CONFIG       = EXEC_DIR + "/" + EXEC_NAME + ".conf"
    MUA_DESKTOP_FILE    = EXEC_DIR + "/" + EXEC_NAME + ".desktop"


if ( os.environ.get('XDG_CONFIG_HOME') != None ):
    USER_CONFIG         = os.environ['XDG_CONFIG_HOME'] + "/" + EXEC_NAME + ".conf"
else:
    USER_CONFIG         = os.environ['HOME'] + "/.config/" + EXEC_NAME + ".conf"

# Exec global config file.
# Position debug statement inside block (twice) so we don't accidently output a
# message if debugging is off
if ( os.path.isfile( GLOBAL_CONFIG ) ):
    execfile( GLOBAL_CONFIG )
    DEBUG( "Including GLOBAL_CONFIG  : " + GLOBAL_CONFIG )
    DEBUG( " |- OK" )
else:
    DEBUG( "Including GLOBAL_CONFIG  : " + GLOBAL_CONFIG )
    DEBUG( " |- DOES NOT EXIST" )

# Exec user config file.
DEBUG( "Including USER_CONFIG    : " + USER_CONFIG )
if ( os.path.isfile( USER_CONFIG ) ):
    execfile( USER_CONFIG )
    DEBUG( " |- OK" )
else:
    DEBUG( " |- DOES NOT EXIST" )

# Let the user know what values are being used:
DEBUG( "CONFIGURATION" )
DEBUG( " |- CHECK_FREQUENCY      : " + str(CHECK_FREQUENCY) )
DEBUG( " |- MUA_DESKTOP_FILE     : " + MUA_DESKTOP_FILE )
DEBUG( " |- MUA_LAUNCH_COMMAND   : " + MUA_LAUNCH_COMMAND )
DEBUG( " |- NOTIFY_TITLE         : " + NOTIFY_TITLE )

class mailIndicator:
    def __init__(self):

        # Register with indicator applet
        DEBUG("Registering with Indicator Applet")
        self.indicator = indicate.indicate_server_ref_default()
        self.indicator.set_type("message.mail")
        self.indicator.set_desktop_file(MUA_DESKTOP_FILE)
        self.indicator.connect("server-display", self.indicator_clicked)
        self.indicators = {}

        # Register with notification system
        if pynotify.init( ("Maildir Indicator") ):
            DEBUG("Registered with Notification system")
            self.notify = True
        else:
            DEBUG("Failed Registeration with Notification system. Continuing without notifications")
            self.notify = False

        # Build list of maildir indicators
        self.buildMenus()

    def buildMenus(self):
        DEBUG("BUILDING maildir list")
        # Loop through the maildirs configured above
        for name, path in MAILDIRS.iteritems():
            DEBUG( " |- " + name )
            # Create mailbox indicator
            new_indicator = indicate.Indicator()
            new_indicator.set_property("name", name)
            new_indicator.set_property("count", "0")
            new_indicator.label = name
            new_indicator.connect("user-display", self.maildir_clicked)

            # Always show it
            new_indicator.show()

            # Save it for later
            self.indicators[name] = new_indicator

    def run(self):
        # This is the main loop
        self.check_mailbox()
        gtk.timeout_add(CHECK_FREQUENCY * 1000, self.check_mailbox)
        gtk.main()

    def maildir_clicked(self, widget, data=None):
        # Not sure how to do this nicely.
        # no-op it for now.
        return True

    def indicator_clicked(self, widget,data=None):
        # Run MUA_LAUNCH_COMMAND
        os.system(MUA_LAUNCH_COMMAND)

    def check_mailbox(self):
        DEBUG("CHECKING for new mail")

        noticecount = 0

        # Check mailboxes for new mail
        for name, path in MAILDIRS.iteritems():
            attention = "false"
            try:
                # Get a count of "new" mail.
                # TODO: Should check for unseen mail in cur?
                count = len( os.listdir(path + "/new") )
                oldcount = self.indicators[name].get_property("count")

                # If there are more messages than previously, then we need to notify about it
                if ( count > int(oldcount) ):
                    noticecount += count
                    attention = "true"
            except:
                # If there was an error, set error
                count = "error"

            DEBUG( " |- " + name + ": " + str(count) + " new messages detected" )


            # Indicate number of new messages
            self.indicators[name].set_property("count", str(count))
            # Set draw-attention if there is more than 0
            self.indicators[name].set_property("draw-attention", attention);

        if ( noticecount > 0 ):
            self.sendnotify(str(noticecount) + " new email messages.")

        return True

    def sendnotify(self, message):
        if not self.notify:
            DEBUG("NOT Sending notification")
            return True

        DEBUG( "Sending notification: '" + message + "'" )
        n = pynotify.Notification(NOTIFY_TITLE, message, "notification-message-email")
        n.show()

        return n

if __name__ == "__main__":
    indicator = mailIndicator()
    indicator.run()
